// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Calculator$ReactHooksTemplate = require("./Calculator.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Calculator$ReactHooksTemplate.make, { }), "calculator");

/*  Not a pure module */
