// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");

function ScaleableTextButton(Props) {
  var t = Props.t;
  var w = Props.w;
  var h = Props.h;
  var s = Props.s;
  var defaultButtonStyle = Css.style(/* :: */Block.simpleVariant("::", [
          Css.fontSize(Css.px(w)),
          /* :: */Block.simpleVariant("::", [
              Css.width(Css.px(w)),
              /* :: */Block.simpleVariant("::", [
                  Css.height(Css.px(h)),
                  /* [] */0
                ])
            ])
        ]));
  var buttonStyle = s !== undefined ? Css.merge(/* :: */Block.simpleVariant("::", [
            s,
            /* :: */Block.simpleVariant("::", [
                defaultButtonStyle,
                /* [] */0
              ])
          ])) : defaultButtonStyle;
  var viewBox = "0 0 " + (String(w) + (" " + String(h)));
  var fontSize = String(w / 2 | 0) + "px";
  return React.createElement("button", {
              className: buttonStyle
            }, React.createElement("svg", {
                  viewBox: viewBox
                }, React.createElement("text", {
                      dx: ".25em",
                      dy: "1em",
                      fontSize: fontSize,
                      x: "0",
                      y: String(w / 2 | 0)
                    }, t)));
}

var make = ScaleableTextButton;

exports.make = make;
/* Css Not a pure module */
